# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: RedCrystalSword
email: redcrystalsword126@1791.com
description: > # this means to ignore newlines until "baseurl:"
  Hello guys! I created this site using Jekyll and Github Pages. I'm mostly going to be using it for test purposes
  (New to web development).
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://redcrystalsword.github.io" # the base hostname & protocol for your site
github_username:  RedCrystalSword

# Build settings
markdown: kramdown

